/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ASM2;



import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class QuanLySinhVien extends javax.swing.JFrame {

    //1. Khai báo biến toàn cục
    ArrayList<Student> list = new ArrayList<>(); // danh sách sinh viên list
    int current = 0; //vị trí hiện hành
    String url = "jdbc:sqlserver://localhost:1433;databasename=DSV";
    String Username = "sa";
    String Password = "123";
    
    public QuanLySinhVien() {
        initComponents();
        setLocationRelativeTo(null);
        //gọi hàm load_data() khi show form lên
        load_data();
    }
    
    //1. Hàm showDetails()
    // Hiện thị thông tin của sinh viên hiện hành lên các controls
    public void showDetails()
    {
        //1. Lấy ra sinh viên hiện hành dựa vào current
        Student stu = list.get(current);
        //2. Gán thông tin của sinh viên lên các controls
        txtMASV.setText(stu.getMasv());
        txtHOTEN.setText(stu.getHoten());
        txtEMAIL.setText(stu.getEmail());
        txtDIENTHOAI.setText(stu.getSoDT());
        if (stu.isGioitinh() == true)
            rdoNAM.setSelected(true);
        else
            rdoNU.setSelected(true);
        txtDIACHI.setText(stu.getDiachi());
        
                
    }

    //2. Hàm load_data() : load dữ liệu từ bảng Students lên list
    public void load_data()
    {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection cn = DriverManager.getConnection(url,Username,Password);
            PreparedStatement ps = cn.prepareStatement("select * from Students");
            ResultSet rs = ps.executeQuery();
            list.clear(); // xóa list đi để lấy dữ liệu từ bảng bỏ vào list
            while(rs.next())
            {
                // tạo đối tượng sinh viên stu
                //Student stu = new Student(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getBoolean(5), rs.getString(6),rs.getString(7));
                Student stu = new Student();
                // gán dữ liệu vào cho các thuộc tính
                stu.setMasv(rs.getString(1));
                stu.setHoten(rs.getString(2));
                stu.setEmail(rs.getString(3));
                stu.setSoDT(rs.getString(4));
                stu.setGioitinh(rs.getBoolean(5));
                stu.setDiachi(rs.getString(6));
                stu.setHinh(rs.getString(7));
                list.add(stu);// thêm đối tượng stu vào danh sách list
            }
            ps.close();
            cn.close();
///////////load từ list lên trên tblSINHVIEN////////            
        //1. lấy mô hình dữ liệu và xóa sạch các hàng
        DefaultTableModel model = (DefaultTableModel) tblSINHVIEN.getModel();
        model.setRowCount(0);
        //2. duyệt qua danh sách sinh viên list, lấy từng sinh viên thêm vào table
        for (Student stu : list) {
            Object[] row = new Object[]{stu.getMasv(),stu.getHoten(),stu.getEmail(),stu.getSoDT(),stu.isGioitinh(),stu.getDiachi(),stu.getHinh()};
            model.addRow(row);
        }               
            
//////////////////////////////////////////////////            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMASV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHOTEN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEMAIL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDIENTHOAI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdoNAM = new javax.swing.JRadioButton();
        rdoNU = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDIACHI = new javax.swing.JTextArea();
        lblHinhanh = new javax.swing.JPanel();
        btnNEW = new javax.swing.JButton();
        btnSAVE = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSINHVIEN = new javax.swing.JTable();
        btnFIRST = new javax.swing.JButton();
        btnPREVIOUS = new javax.swing.JButton();
        btnNEXT = new javax.swing.JButton();
        btnLAST = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhân Viên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quản Lý Sinh Viên");

        jLabel2.setText("Mã SV:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Email:");

        jLabel5.setText("Số điện thoại:");

        jLabel6.setText("Giới tính:");

        buttonGroup1.add(rdoNAM);
        rdoNAM.setText("Nam");

        buttonGroup1.add(rdoNU);
        rdoNU.setText("Nữ");

        jLabel7.setText("Địa chỉ:");

        txtDIACHI.setColumns(20);
        txtDIACHI.setRows(5);
        jScrollPane1.setViewportView(txtDIACHI);

        lblHinhanh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblHinhanh.setToolTipText("");
        lblHinhanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhanhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lblHinhanhLayout = new javax.swing.GroupLayout(lblHinhanh);
        lblHinhanh.setLayout(lblHinhanhLayout);
        lblHinhanhLayout.setHorizontalGroup(
            lblHinhanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );
        lblHinhanhLayout.setVerticalGroup(
            lblHinhanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        btnNEW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASM2/new.png"))); // NOI18N
        btnNEW.setText("New");
        btnNEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNEWActionPerformed(evt);
            }
        });

        btnSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASM2/save.png"))); // NOI18N
        btnSAVE.setText("Save");
        btnSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAVEActionPerformed(evt);
            }
        });

        btnDELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASM2/delete.png"))); // NOI18N
        btnDELETE.setText("Delete");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });

        btnUPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASM2/update-icon.png"))); // NOI18N
        btnUPDATE.setText("Update");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        tblSINHVIEN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ tên", "Email", "Số điện thoại", "Giới tính", "Địa chỉ", "hình"
            }
        ));
        tblSINHVIEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSINHVIENMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSINHVIEN);

        btnFIRST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASM2/FIRST.png"))); // NOI18N
        btnFIRST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFIRSTActionPerformed(evt);
            }
        });

        btnPREVIOUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASM2/PREVIOUS.png"))); // NOI18N
        btnPREVIOUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPREVIOUSActionPerformed(evt);
            }
        });

        btnNEXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASM2/NEXT.png"))); // NOI18N
        btnNEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNEXTActionPerformed(evt);
            }
        });

        btnLAST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASM2/LAST.png"))); // NOI18N
        btnLAST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLASTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtMASV)
                                                    .addComponent(txtHOTEN)
                                                    .addComponent(txtEMAIL)
                                                    .addComponent(txtDIENTHOAI, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(rdoNAM)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(rdoNU)))
                                                .addGap(71, 71, 71)
                                                .addComponent(lblHinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnDELETE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnNEW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnUPDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnSAVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(btnFIRST, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPREVIOUS, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLAST, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMASV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtHOTEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtDIENTHOAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblHinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdoNAM)
                    .addComponent(rdoNU))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNEW)
                                .addComponent(btnSAVE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDELETE)
                                .addComponent(btnUPDATE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFIRST)
                    .addComponent(btnPREVIOUS)
                    .addComponent(btnNEXT)
                    .addComponent(btnLAST))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void insert()
    {
                
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection cn = DriverManager.getConnection(url,Username,Password);
            PreparedStatement ps = cn.prepareStatement("insert into Students values(?,?,?,?,?,?,?) ");
            //1. Truyền giá trị từ các control vào đối số 
            ps.setString(1, txtMASV.getText());
            ps.setString(2, txtHOTEN.getText());
            ps.setString(3, txtEMAIL.getText());
            ps.setString(4, txtDIENTHOAI.getText());
            //2. Nếu chọn rdoNAM.isSelected()==true thì trả về true...ngoặc lại trả về false
            //Nam là true và Nữ là false
            ps.setBoolean(5, (rdoNAM.isSelected()==true)?true:false);
            ps.setString(6, txtDIACHI.getText());
            ps.setString(7, "teo.jpg"); // hình làm sau
            // thực thi : kq = 1 thành công kq = 0 thất bại.
            int kq = ps.executeUpdate();
            if (kq == 1)
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công.");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại.");
            }
            //3. Thêm xong rồi nhớ đóng kết nối.
            ps.close();
            cn.close();
            //4. nhớ gọi lại load_data() để load dữ liệu mới lên jtable
            this.load_data();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm Không Thành Công.");
            e.printStackTrace();
        }
    }
    
    private void btnSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAVEActionPerformed
        // TODO add your handling code here:
        //insert into Students values('PS001',N'Nguyễn Văn Tèo','teo@gmail.com','0907774677',1,N'123 Hai Bà Trưng','teo.jpg')
        //go
        this.insert();
    }//GEN-LAST:event_btnSAVEActionPerformed

    private void btnPREVIOUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPREVIOUSActionPerformed
        if(current>0){
            current--;
            showDetails();
        }
    }//GEN-LAST:event_btnPREVIOUSActionPerformed

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        // TODO add your handling code here:
        
        
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection cn = DriverManager.getConnection(url,Username,Password);
            PreparedStatement ps = cn.prepareStatement("delete from Students where masv = ? ");
            //1. Truyền giá trị từ các control vào đối số 
            ps.setString(1, txtMASV.getText());
            // thực thi : kq = 1 thành công kq = 0 thất bại.
            int kq = ps.executeUpdate();
            if (kq == 1)
            {
                JOptionPane.showMessageDialog(this, "Xóa thành công.");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Xóa thất bại.");
            }
            //3. Thêm xong rồi nhớ đóng kết nối.
            ps.close();
            cn.close();
            //4. nhớ gọi lại load_data() để load dữ liệu mới lên jtable
            this.load_data();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa Không Thành Công.");
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        // TODO add your handling code here:
       try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection cn = DriverManager.getConnection(url,Username,Password);
            PreparedStatement ps = cn.prepareStatement("update Students set hoten=?, email = ?, SoDT = ?, gioitinh = ?, diachi = ?, hinh = ?  where masv = ? ");
            //1. Truyền giá trị từ các control vào đối số 
            ps.setString(7, txtMASV.getText());
            ps.setString(1, txtHOTEN.getText());
            ps.setString(2, txtEMAIL.getText());
            ps.setString(3, txtDIENTHOAI.getText());
            //2. Nếu chọn rdoNAM.isSelected()==true thì trả về true...ngoặc lại trả về false
            //Nam là true và Nữ là false
            ps.setBoolean(4, (rdoNAM.isSelected()==true)?true:false);
            ps.setString(5, txtDIACHI.getText());
            ps.setString(6, "teo.jpg"); // hình làm sau
            // thực thi : kq = 1 thành công kq = 0 thất bại.
            int kq = ps.executeUpdate();
            if (kq == 1)
            {
                JOptionPane.showMessageDialog(this, "Sửa thành công.");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sửa thất bại.");
            }
            //3. Update xong rồi nhớ đóng kết nối.
            ps.close();
            cn.close();
            //4. nhớ gọi lại load_data() để load dữ liệu mới lên jtable
            this.load_data();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sửa Không Thành Công.");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnFIRSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFIRSTActionPerformed
       current = 0;
        showDetails();
        
    }//GEN-LAST:event_btnFIRSTActionPerformed

    private void btnNEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNEXTActionPerformed
        if(current<list.size()-1){
            current ++;
            showDetails();
        }
        
        
    }//GEN-LAST:event_btnNEXTActionPerformed

    private void btnLASTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLASTActionPerformed
        current = list.size() - 1;
        showDetails();
        
        
    }//GEN-LAST:event_btnLASTActionPerformed

    private void tblSINHVIENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSINHVIENMouseClicked
        // TODO add your handling code here:
        //1. Xác định dòng vừa click vào
        current = tblSINHVIEN.getSelectedRow();
        //JOptionPane.showMessageDialog(this, ""+ current);
        //2. gọi hàm hiện thị thông tin chi tiết lên controls
        showDetails();
    }//GEN-LAST:event_tblSINHVIENMouseClicked

    private void btnNEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNEWActionPerformed
        // TODO add your handling code here:
        txtMASV.setText("");
        txtHOTEN.setText("");
        txtEMAIL.setText("");
        txtDIENTHOAI.setText("");
        rdoNAM.setSelected(true);
        txtDIACHI.setText("");
        txtMASV.requestFocus(); // con nháy mặc định ở txtMASV
    }//GEN-LAST:event_btnNEWActionPerformed

    private void lblHinhanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhanhMouseClicked
      
    }//GEN-LAST:event_lblHinhanhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnFIRST;
    private javax.swing.JButton btnLAST;
    private javax.swing.JButton btnNEW;
    private javax.swing.JButton btnNEXT;
    private javax.swing.JButton btnPREVIOUS;
    private javax.swing.JButton btnSAVE;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lblHinhanh;
    private javax.swing.JRadioButton rdoNAM;
    private javax.swing.JRadioButton rdoNU;
    private javax.swing.JTable tblSINHVIEN;
    private javax.swing.JTextArea txtDIACHI;
    private javax.swing.JTextField txtDIENTHOAI;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtHOTEN;
    private javax.swing.JTextField txtMASV;
    // End of variables declaration//GEN-END:variables
}
